### ISSUE TITLE
what if only part of `buf`'s content got written?The remaining content will be discarded?

### ISSUE THREAD

**Issue by yfaming** [hjr3/mob#21]
https://github.com/hjr3/mob/blob/2c9e582c61bb5ecbf8e33745115e19a7419f3fe4/src/main.rs#L371-L373

**Comment by hjr3** [comment]
Good find! I should be pushing back on to the queue if the entire message was not written.

**Comment by hjr3** [comment]
@yfaming you linked to an older part of the code. was that from a blog post? I only fixed the latest version.

**Comment by yfaming** [comment]
@hjr3 yeah I just got there through your blog. Thanks for your great blog posts, they're of great help!
